option(GSPLAT_CUDA "Build Inria CUDA rasterizer" ON)

set(GSPLAT_CUDA_ENABLED 0)
if(NOT GSPLAT_CUDA)
    return()
endif()

if(GSPLAT_USE_CUDA_TOOLCHAIN)
    if(EXISTS "${PROJECT_SOURCE_DIR}/cmake/cuda_compiler_cache.cmake")
        include("${PROJECT_SOURCE_DIR}/cmake/cuda_compiler_cache.cmake")
    elseif(EXISTS "${CMAKE_CURRENT_LIST_DIR}/cuda_compiler_cache.cmake")
        include("${CMAKE_CURRENT_LIST_DIR}/cuda_compiler_cache.cmake")
    endif()
elseif(MSVC)
    set(_nvcc_host
        "-allow-unsupported-compiler"
        "-Xcompiler=/D__NV_NO_HOST_COMPILER_CHECK"
        "-Xcompiler=/D_ALLOW_COMPILER_AND_STL_VERSION_MISMATCH"
        "-Xcompiler=/Zc:preprocessor")
    string(JOIN " " _nvcc_host_str ${_nvcc_host})
    set(CMAKE_CUDA_FLAGS "${_nvcc_host_str} ${CMAKE_CUDA_FLAGS}")
endif()

set(_cuda_ready FALSE)
if(CMAKE_CUDA_COMPILER)
    if(NOT CMAKE_CUDA_COMPILER_LOADED)
        enable_language(CUDA)
    endif()
    set(_cuda_ready TRUE)
else()
    include(CheckLanguage)
    check_language(CUDA)
    if(CMAKE_CUDA_COMPILER)
        if(NOT CMAKE_CUDA_ARCHITECTURES)
            set(CMAKE_CUDA_ARCHITECTURES "61;70;75;86")
        endif()
        enable_language(CUDA)
        set(_cuda_ready TRUE)
    endif()
endif()

if(NOT _cuda_ready)
    message(STATUS "No CUDA compiler — gsplat_raster CPU-only stubs")
    return()
endif()

find_package(CUDAToolkit REQUIRED)
set(GSPLAT_CUDART_LINK CUDA::cudart)
message(STATUS "gsplat-raster-sdk: nvcc ${CMAKE_CUDA_COMPILER_VERSION}, CUDAToolkit ${CUDAToolkit_VERSION}")
if(NOT DEFINED GSPLAT_DGR_ROOT)
    get_filename_component(_gsplat_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
    set(GSPLAT_DGR_ROOT "${_gsplat_root}/third_party/diff-gaussian-rasterization")
endif()
if(NOT EXISTS "${GSPLAT_DGR_ROOT}/cuda_rasterizer/rasterizer.h")
    message(FATAL_ERROR
        "Missing vendored diff-gaussian-rasterization at ${GSPLAT_DGR_ROOT}. "
        "External fallback paths are disabled.")
endif()
if(NOT EXISTS "${GSPLAT_DGR_ROOT}/third_party/glm/glm/glm.hpp")
    message(FATAL_ERROR "Missing glm in diff-gaussian-rasterization (git submodule update --init)")
endif()

add_subdirectory("${GSPLAT_DGR_ROOT}" "${CMAKE_BINARY_DIR}/diff-gaussian-rasterization")

if(CMAKE_CUDA_COMPILER_VERSION VERSION_GREATER_EQUAL "13.0")
    set(_archs "75")
elseif(CMAKE_CUDA_COMPILER_VERSION VERSION_GREATER_EQUAL "12.0")
    set(_archs "61;75;86")
else()
    set(_archs "61;70;75;86")
endif()
set_target_properties(CudaRasterizer PROPERTIES CUDA_ARCHITECTURES "${_archs}")
set(GSPLAT_CUDA_ENABLED 1)
message(STATUS "gsplat-raster-sdk: CudaRasterizer enabled (${_archs})")
